version: "3"

services:
  pagai:
    image: arkhn/pagai:latest
    build:
      context: .
    env_file: .env.docker
    volumes:
      - ./models:/srv/pagai/models
    ports:
      - 8081:8081
      - 5000:5000
