version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pagai:
    build:
      context: .
      dockerfile: Dockerfile.test
    # keep container alive for test commands with `docker-compose exec`
    command: tail -F anything
    working_dir: /app
    env_file: .env.docker
    environment:
      - TEST_ORACLE_HOST
      - TEST_ORACLE_PORT
      - TEST_ORACLE_DB
      - TEST_ORACLE_LOGIN
      - TEST_ORACLE_PASSWORD
    volumes:
      - .:/app
      - ./models:/srv/pagai/models

volumes:
  postgres-data:
