version: "3.7"

services:
  reverse-proxy:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - pagai
    networks:
      - arkhn

  pagai:
    image: arkhn/pagai:latest
    build:
      context: .
    volumes:
      - ./models:/srv/pagai/models
    ports:
      - 4000:4000
    networks:
      - arkhn

networks:
  arkhn:
    name: arkhn_network
