sql:
    training_database:
        database: 'mimic'
        user: '***'
        options: #'--search_path=mimiciii'

    prod_database:
        database: 'mimic'
        user: '***'
        options: #'--search_path=mimiciii'
