sql:
    training_database:
        database: 'mimic'
        user: "ryffel"
        options: '--search_path=mimiciii'

    prod_database:
        database: 'mimic'
        user: "ryffel"
        options: '--search_path=mimiciii'
graph:
    include_threshold: 0.5
    str_id_max_unique_values: 40
model:
    min_score: 0.1

