name: pagai

on: [push]

jobs:
  tests:
    name: Lint and test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Setup docker for tests
        run: make docker-setup-tests
        env:
          TEST_ORACLE_HOST: ${{ secrets.TEST_ORACLE_HOST }}
          TEST_ORACLE_PORT: ${{ secrets.TEST_ORACLE_PORT }}
          TEST_ORACLE_DB: ${{ secrets.TEST_ORACLE_DB }}
          TEST_ORACLE_LOGIN: ${{ secrets.TEST_ORACLE_LOGIN }}
          TEST_ORACLE_PASSWORD: ${{ secrets.TEST_ORACLE_PASSWORD }}
      - name: Lint with flake8
        run: make lint
      - name: Test with pytest
        run: make tests

  publish:
    name: Build and publish
    runs-on: ubuntu-18.04

    needs: tests
    if: github.ref == 'refs/heads/master'

    env:
      ARKHN_REGISTRY: mammouth.arkhn.com
      IMAGE: arkhn/pagai
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Build images
        run: |
          docker build -t $IMAGE .
          docker build -f Dockerfile.oracle11 -t $ARKHN_REGISTRY/$IMAGE:oracle11 .

      - name: Tag images
        run: |
          docker tag $IMAGE $IMAGE:latest
          docker tag $IMAGE $IMAGE:$GITHUB_SHA

      - name: Publish to the docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker push $IMAGE:latest
          docker push $IMAGE:$GITHUB_SHA

      - name: Publish to arkhn regitry (mammouth)
        run: |
          echo "${{ secrets.ARKHN_DOCKER_PASSWORD }}" | docker login $ARKHN_REGISTRY -u ${{ secrets.ARKHN_DOCKER_LOGIN }} --password-stdin
          docker push $ARKHN_REGISTRY/$IMAGE:oracle11
